[package]
name = "rusty-starter"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
dialoguer = {version = "0.11.0", features = ["fuzzy-select"]}
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.14"
